/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPActualizarClientes extends javax.swing.JPanel {

    /**
     * Creates new form JPImprimirClientes
     */
    PreparedStatement st;
    ResultSet rs;
    int idCliente;
    
    public JPActualizarClientes() {
        initComponents();
        //**MOSTRAR TABLA CLIENTES
        try {
            String query = "SELECT * FROM cliente";
            
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmcliente = new DefaultTableModel();
            
            jTClientes.setModel(dfmcliente);
            dfmcliente.setColumnIdentifiers(new Object[] {"ID","NOMBRE","APELLIDO", "NIT", "DIRECCION","TELEFONO"});

            while (rs.next()){
             
                
                dfmcliente.addRow(new Object[] {rs.getInt("idcliente"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("nit"),rs.getString("direccion"),rs.getString("telefono")});
            }
            
        }catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
        
        //*************************************************************************
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFApellidoClienteActualizar = new javax.swing.JTextField();
        jTFNitClienteActualizarr = new javax.swing.JTextField();
        jTFDireccionClienteActualizar = new javax.swing.JTextField();
        jTFTelefonoClienteActualizar = new javax.swing.JTextField();
        jBCancelarClienteActualizar = new javax.swing.JButton();
        jBHechoClienteActualizar = new javax.swing.JButton();
        jTFNombreClienteActualizar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("ACTUALIZAR  CLIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, -10, 300, 260));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("NIT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Direccion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Telefono");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, -1, -1));

        jTFApellidoClienteActualizar.setBackground(java.awt.Color.white);
        jTFApellidoClienteActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFApellidoClienteActualizar.setForeground(java.awt.Color.black);
        add(jTFApellidoClienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 310, 40));

        jTFNitClienteActualizarr.setBackground(java.awt.Color.white);
        jTFNitClienteActualizarr.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNitClienteActualizarr.setForeground(java.awt.Color.black);
        add(jTFNitClienteActualizarr, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 240, 320, 40));

        jTFDireccionClienteActualizar.setBackground(java.awt.Color.white);
        jTFDireccionClienteActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDireccionClienteActualizar.setForeground(java.awt.Color.black);
        add(jTFDireccionClienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 320, 320, 40));

        jTFTelefonoClienteActualizar.setBackground(java.awt.Color.white);
        jTFTelefonoClienteActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoClienteActualizar.setForeground(java.awt.Color.black);
        add(jTFTelefonoClienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, 320, 40));

        jBCancelarClienteActualizar.setBackground(java.awt.Color.red);
        jBCancelarClienteActualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBCancelarClienteActualizar.setForeground(java.awt.Color.black);
        jBCancelarClienteActualizar.setText("Cancelar");
        jBCancelarClienteActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarClienteActualizarActionPerformed(evt);
            }
        });
        add(jBCancelarClienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 480, 170, 70));

        jBHechoClienteActualizar.setBackground(java.awt.Color.green);
        jBHechoClienteActualizar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBHechoClienteActualizar.setForeground(java.awt.Color.black);
        jBHechoClienteActualizar.setText("Hecho");
        jBHechoClienteActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHechoClienteActualizarActionPerformed(evt);
            }
        });
        add(jBHechoClienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 480, 170, 70));

        jTFNombreClienteActualizar.setBackground(java.awt.Color.white);
        jTFNombreClienteActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreClienteActualizar.setForeground(java.awt.Color.black);
        add(jTFNombreClienteActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 300, 40));

        jTClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 780, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void jTClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientesMouseClicked
        // TODO add your handling code here:
         int seleccionar = jTClientes.rowAtPoint(evt.getPoint());
         this.idCliente = (int) jTClientes.getValueAt(seleccionar, 0);
         String nombre = (String) jTClientes.getValueAt(seleccionar, 1);
         jTFNombreClienteActualizar.setText(nombre);
         String apellido = (String) jTClientes.getValueAt(seleccionar,2);
         jTFApellidoClienteActualizar.setText(apellido);
         String nitCliente = (String) jTClientes.getValueAt(seleccionar, 3);
         jTFNitClienteActualizarr.setText(nitCliente);
         String direccion = (String) jTClientes.getValueAt(seleccionar,4);
         jTFDireccionClienteActualizar.setText(direccion);
         String telefono = (String) jTClientes.getValueAt(seleccionar, 5);
         jTFTelefonoClienteActualizar.setText(telefono);
         
     
    }//GEN-LAST:event_jTClientesMouseClicked

    private void jBHechoClienteActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHechoClienteActualizarActionPerformed
        // TODO add your handling code here:
        String nombre = jTFNombreClienteActualizar.getText();
        String apellido =jTFApellidoClienteActualizar.getText();
        String nitCliente = jTFNitClienteActualizarr.getText();
        String direccion = jTFDireccionClienteActualizar.getText();
        String telefono = jTFTelefonoClienteActualizar.getText();
        
        
        try{
            String queryactualizar = "UPDATE cliente SET nombre='"+nombre+"',apellido='"+apellido+"',nit='"+nitCliente+"',direccion='"+direccion+"',telefono='"+telefono+"' WHERE idcliente='"+idCliente+"'";
            st=conexion.getConection().prepareStatement(queryactualizar);
            st.executeUpdate();
            
            jTFNombreClienteActualizar.setText("");
            jTFApellidoClienteActualizar.setText("");
            jTFNitClienteActualizarr.setText("");
            jTFDireccionClienteActualizar.setText("");
            jTFTelefonoClienteActualizar.setText("");
            
            //**MOSTRAR TABLA CLIENTES
        try {
            String query = "SELECT * FROM cliente";
            
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmcliente = new DefaultTableModel();
            
            jTClientes.setModel(dfmcliente);
            dfmcliente.setColumnIdentifiers(new Object[] {"ID","NOMBRE","APELLIDO", "NIT", "DIRECCION","TELEFONO"});

            while (rs.next()){
             
                
                dfmcliente.addRow(new Object[] {rs.getInt("idcliente"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("nit"),rs.getString("direccion"),rs.getString("telefono")});
            }
            
        }catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
        
        //*************************************************************************
            
            
        }catch(SQLException ex){
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_jBHechoClienteActualizarActionPerformed

    private void jBCancelarClienteActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarClienteActualizarActionPerformed
        // TODO add your handling code here:
        
            jTFNombreClienteActualizar.setText("");
            jTFApellidoClienteActualizar.setText("");
            jTFNitClienteActualizarr.setText("");
            jTFDireccionClienteActualizar.setText("");
            jTFTelefonoClienteActualizar.setText("");
    }//GEN-LAST:event_jBCancelarClienteActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarClienteActualizar;
    private javax.swing.JButton jBHechoClienteActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JTextField jTFApellidoClienteActualizar;
    private javax.swing.JTextField jTFDireccionClienteActualizar;
    private javax.swing.JTextField jTFNitClienteActualizarr;
    private javax.swing.JTextField jTFNombreClienteActualizar;
    private javax.swing.JTextField jTFTelefonoClienteActualizar;
    // End of variables declaration//GEN-END:variables
}
