/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;
import packagemodelo.rolusuario;

/**
 *
 * @author Administrator
 */
public class JPActualizarUsuario extends javax.swing.JPanel {

    /**
     * Creates new form JPActualizarUsuario
     */
    
    
    PreparedStatement st;
    ResultSet rs;
    int idUsuario;
    
    
    public JPActualizarUsuario() {
        initComponents();
        
        rolusuario roles= new rolusuario();
        DefaultComboBoxModel modelorol = new DefaultComboBoxModel(roles.mostrarRoles());
        jCBRolUsuario.setModel(modelorol);
        
         //MOSTRAR TABLA USUARIOS
        try {
            String query="SELECT * FROM usuario";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmusuarios = new DefaultTableModel();
    
            jTUsuarios.setModel(dfmusuarios);
            
            dfmusuarios.setColumnIdentifiers(new Object[] {"ID","NOMBRE","APELLIDO","DIRECCION","TELEFONO","CARGO","USUARIO","CONTRASEÑA","CORREO ELECTRONICO","CUI"});
            
            while(rs.next()){
                
                dfmusuarios.addRow(new Object[] {rs.getInt("idusuario"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("direccion"),rs.getString("telefono"),rs.getString("cargo"),rs.getString("usuario"),rs.getString("contrasenia"),rs.getString("correoelectronico"),rs.getString("cui")});
                
            }
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
        }
       //**************************************************** 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTTNombreUsuarioActualizar = new javax.swing.JTextField();
        jTFApellidoUsuarioActualizar = new javax.swing.JTextField();
        jTFDireccionUsuarioActualizar = new javax.swing.JTextField();
        jTFTelefonoUsuarioActualizar = new javax.swing.JTextField();
        jTFCargoUsuarioActualizar = new javax.swing.JTextField();
        jTFUsuarioUsuarioActualizar = new javax.swing.JTextField();
        jTFContraseñaUsuarioActualizar = new javax.swing.JTextField();
        jTFCorreoUsuarioActualizar = new javax.swing.JTextField();
        jTFCuiUsuarioActualizar = new javax.swing.JTextField();
        jBCancelarUsuariosActualizar = new javax.swing.JButton();
        jBAceptarUsuariosActualizar = new javax.swing.JButton();
        jCBRolUsuario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Actualizar Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Direccion");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Telefono ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Cargo");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Usuario");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Contraseña");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Correo electronico");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("CUI");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 330, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Rol");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 400, -1, -1));

        jTTNombreUsuarioActualizar.setBackground(java.awt.Color.white);
        jTTNombreUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTTNombreUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTTNombreUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 120, 300, 30));

        jTFApellidoUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFApellidoUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFApellidoUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFApellidoUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 300, -1));

        jTFDireccionUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFDireccionUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDireccionUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFDireccionUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 300, -1));

        jTFTelefonoUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFTelefonoUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFTelefonoUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 300, -1));

        jTFCargoUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFCargoUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFCargoUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFCargoUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 300, -1));

        jTFUsuarioUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFUsuarioUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFUsuarioUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFUsuarioUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 120, 280, -1));

        jTFContraseñaUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFContraseñaUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFContraseñaUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFContraseñaUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 290, -1));

        jTFCorreoUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFCorreoUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFCorreoUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFCorreoUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 290, -1));

        jTFCuiUsuarioActualizar.setBackground(java.awt.Color.white);
        jTFCuiUsuarioActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFCuiUsuarioActualizar.setForeground(java.awt.Color.black);
        add(jTFCuiUsuarioActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 360, 300, -1));

        jBCancelarUsuariosActualizar.setBackground(java.awt.Color.red);
        jBCancelarUsuariosActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarUsuariosActualizar.setForeground(java.awt.Color.black);
        jBCancelarUsuariosActualizar.setText("Cancelar");
        add(jBCancelarUsuariosActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        jBAceptarUsuariosActualizar.setBackground(java.awt.Color.green);
        jBAceptarUsuariosActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarUsuariosActualizar.setForeground(java.awt.Color.black);
        jBAceptarUsuariosActualizar.setText("Aceptar");
        jBAceptarUsuariosActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarUsuariosActualizarActionPerformed(evt);
            }
        });
        add(jBAceptarUsuariosActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 510, -1, -1));

        jCBRolUsuario.setBackground(java.awt.Color.white);
        jCBRolUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCBRolUsuario.setForeground(java.awt.Color.black);
        jCBRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jCBRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 430, 300, -1));

        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 690, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTUsuariosMouseClicked
        // TODO add your handling code here:
         int seleccionar = jTUsuarios.rowAtPoint(evt.getPoint());
         this.idUsuario = (int) jTUsuarios.getValueAt(seleccionar, 0);
         String nombre = (String) jTUsuarios.getValueAt(seleccionar,1);
         jTTNombreUsuarioActualizar.setText(nombre);
         String apellido = (String) jTUsuarios.getValueAt(seleccionar,2);
         jTFApellidoUsuarioActualizar.setText(apellido);
         String direccion = (String) jTUsuarios.getValueAt(seleccionar, 3);
         jTFDireccionUsuarioActualizar.setText(direccion);
         String telefono = (String) jTUsuarios.getValueAt(seleccionar, 4);
         jTFTelefonoUsuarioActualizar.setText(telefono);
         String cargo = (String) jTUsuarios.getValueAt(seleccionar, 5);
         jTFCargoUsuarioActualizar.setText(cargo);
         String usuario = (String) jTUsuarios.getValueAt(seleccionar, 6);
         jTFUsuarioUsuarioActualizar.setText(usuario);
         String contrasenia = (String) jTUsuarios.getValueAt(seleccionar, 7);
         jTFContraseñaUsuarioActualizar.setText(contrasenia);
         String correoelectronico = (String)jTUsuarios.getValueAt(seleccionar,8);
         jTFCorreoUsuarioActualizar.setText(correoelectronico);
         String cuiusuario = (String) jTUsuarios.getValueAt(seleccionar, 9);
         jTFCuiUsuarioActualizar.setText(cuiusuario);
         
         
        
    }//GEN-LAST:event_jTUsuariosMouseClicked

    private void jBAceptarUsuariosActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarUsuariosActualizarActionPerformed
        // TODO add your handling code here:
        
        String nombreUsuario = jTTNombreUsuarioActualizar.getText();
        String apellidoUsuario = jTFApellidoUsuarioActualizar.getText();
        String direccionUsuario = jTFDireccionUsuarioActualizar.getText();
        String telefonoUsuario = jTFTelefonoUsuarioActualizar.getText();
        String cargoUsuario = jTFCargoUsuarioActualizar.getText();
        String usuario= jTFUsuarioUsuarioActualizar.getText();
        String contrasenia = jTFContraseñaUsuarioActualizar.getText();
        String correo = jTFCorreoUsuarioActualizar.getText();
        String cui = jTFCuiUsuarioActualizar.getText();
        
        rolusuario rol = (rolusuario) jCBRolUsuario.getSelectedItem();
        int rolseleccionado=  rol.getIdrol();
        
        try {
              String queryactualizar="UPDATE usuario SET nombre='"+nombreUsuario+"',apellido='"+apellidoUsuario+"',direccion='"+direccionUsuario+"',telefono='"+telefonoUsuario+"',cargo='"+cargoUsuario+"',usuario='"+usuario+"',contrasenia='"+contrasenia+"',correoelectronico='"+correo+"',cui='"+cui+"',rol_idrol='"+rolseleccionado+"' WHERE idusuario='"+idUsuario+"'";
                                
             st= conexion.getConection().prepareStatement(queryactualizar);
             st.executeUpdate();
             
            jTTNombreUsuarioActualizar.setText("");
            jTFApellidoUsuarioActualizar.setText("");
            jTFDireccionUsuarioActualizar.setText("");
            jTFTelefonoUsuarioActualizar.setText("");
            jTFCargoUsuarioActualizar.setText("");
            jTFUsuarioUsuarioActualizar.setText("");
            jTFContraseñaUsuarioActualizar.setText("");
            jTFCorreoUsuarioActualizar.setText("");
            jTFCuiUsuarioActualizar.setText("");
            
              //MOSTRAR TABLA USUARIOS
        try {
            String query="SELECT * FROM usuario";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmusuarios = new DefaultTableModel();
    
            jTUsuarios.setModel(dfmusuarios);
            
            dfmusuarios.setColumnIdentifiers(new Object[] {"ID","NOMBRE","APELLIDO","DIRECCION","TELEFONO","CARGO","USUARIO","CONTRASEÑA","CORREO ELECTRONICO","CUI"});
            
            while(rs.next()){
                
                dfmusuarios.addRow(new Object[] {rs.getInt("idusuario"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("direccion"),rs.getString("telefono"),rs.getString("cargo"),rs.getString("usuario"),rs.getString("contrasenia"),rs.getString("correoelectronico"),rs.getString("cui")});
                
            }
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
        }
       //**************************************************** 
            
            
             
              
            }catch(SQLException ex){
                System.out.println(ex.toString());
            }
        
        
    }//GEN-LAST:event_jBAceptarUsuariosActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarUsuariosActualizar;
    private javax.swing.JButton jBCancelarUsuariosActualizar;
    private javax.swing.JComboBox<String> jCBRolUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFApellidoUsuarioActualizar;
    private javax.swing.JTextField jTFCargoUsuarioActualizar;
    private javax.swing.JTextField jTFContraseñaUsuarioActualizar;
    private javax.swing.JTextField jTFCorreoUsuarioActualizar;
    private javax.swing.JTextField jTFCuiUsuarioActualizar;
    private javax.swing.JTextField jTFDireccionUsuarioActualizar;
    private javax.swing.JTextField jTFTelefonoUsuarioActualizar;
    private javax.swing.JTextField jTFUsuarioUsuarioActualizar;
    private javax.swing.JTextField jTTNombreUsuarioActualizar;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
