/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;
import packagemodelo.categoria;

/**
 *
 * @author Administrator
 */
public class JPActualizarProductos extends javax.swing.JPanel {

    /**
     * Creates new form JPActualizarProductos
     */
     PreparedStatement st;
     ResultSet rs;
     int idProducto;
     float preciocosto, precioventa;
     int existencia;
    
     
    public JPActualizarProductos() {
        initComponents();
        //COMBOBOX CATEGORIAS
       // categoria cc = new categoria();
        //DefaultComboBoxModel modelocategoria = new DefaultComboBoxModel(cc.mostrarCategorias());
         categoria categorias = new categoria();
         DefaultComboBoxModel modelocategoria = new DefaultComboBoxModel(categorias.mostrarCategorias());
        jCBCategoriaProductoActualizar.setModel(modelocategoria);
        
        //********************************************************************************
        //MOSTRAR TABLA CON PRODUCTOS  
        try {
            String query = "SELECT * FROM producto";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTMostrarProductos.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE","DESCRIPCION", "PRECIO COSTO", "PRECIO VENTEA","EXISTENCIA"});

            while (rs.next()){
             
                
                dfmproducto.addRow(new Object[] {rs.getInt("idproducto"),rs.getString("nombre"),rs.getString("descripcion"),rs.getFloat("preciocosto"),rs.getFloat("precioventa"),rs.getInt("existencia")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
            
        //**************************************************************************************************************************************************
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFNombreProductoActualizar = new javax.swing.JTextField();
        jTFPrecioCostoActualizar = new javax.swing.JTextField();
        jTFPrecioVentaActualizar = new javax.swing.JTextField();
        jTFExistenciaActualizar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFDescripcionProductoActualizar = new javax.swing.JTextArea();
        jBCancelarProductoActualizar = new javax.swing.JButton();
        jBAceptarProductoActualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jCBCategoriaProductoActualizar = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMostrarProductos = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(1300, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 240, 160));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("ACTUALIZAR PRODUCTOS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Precio costo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Precio venta");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Existencia");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Descripcion");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 500, -1, -1));

        jTFNombreProductoActualizar.setBackground(java.awt.Color.white);
        jTFNombreProductoActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreProductoActualizar.setForeground(java.awt.Color.black);
        add(jTFNombreProductoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 200, 280, -1));

        jTFPrecioCostoActualizar.setBackground(java.awt.Color.white);
        jTFPrecioCostoActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFPrecioCostoActualizar.setForeground(java.awt.Color.black);
        add(jTFPrecioCostoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 260, 280, -1));

        jTFPrecioVentaActualizar.setBackground(java.awt.Color.white);
        jTFPrecioVentaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFPrecioVentaActualizar.setForeground(java.awt.Color.black);
        add(jTFPrecioVentaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 320, 280, -1));

        jTFExistenciaActualizar.setBackground(java.awt.Color.white);
        jTFExistenciaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFExistenciaActualizar.setForeground(java.awt.Color.black);
        add(jTFExistenciaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 280, -1));

        jScrollPane1.setForeground(java.awt.Color.white);

        jTFDescripcionProductoActualizar.setBackground(java.awt.Color.white);
        jTFDescripcionProductoActualizar.setColumns(20);
        jTFDescripcionProductoActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDescripcionProductoActualizar.setRows(5);
        jScrollPane1.setViewportView(jTFDescripcionProductoActualizar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 480, -1, 80));

        jBCancelarProductoActualizar.setBackground(java.awt.Color.red);
        jBCancelarProductoActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarProductoActualizar.setForeground(java.awt.Color.black);
        jBCancelarProductoActualizar.setText("Cancelar");
        jBCancelarProductoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarProductoActualizarActionPerformed(evt);
            }
        });
        add(jBCancelarProductoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, -1, -1));

        jBAceptarProductoActualizar.setBackground(java.awt.Color.green);
        jBAceptarProductoActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarProductoActualizar.setForeground(java.awt.Color.black);
        jBAceptarProductoActualizar.setText("Aceptar");
        jBAceptarProductoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarProductoActualizarActionPerformed(evt);
            }
        });
        add(jBAceptarProductoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 580, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Categoría");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 450, -1, 20));

        jCBCategoriaProductoActualizar.setBackground(java.awt.Color.white);
        jCBCategoriaProductoActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCBCategoriaProductoActualizar.setForeground(java.awt.Color.black);
        jCBCategoriaProductoActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jCBCategoriaProductoActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, 280, -1));

        jTMostrarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio costo", "Precio venta", "Existencia", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTMostrarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMostrarProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTMostrarProductos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 850, 560));
    }// </editor-fold>//GEN-END:initComponents

    private void jTMostrarProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMostrarProductosMouseClicked
        // TODO add your handling code here:
        
        int seleccionar = jTMostrarProductos.rowAtPoint(evt.getPoint());
        this.idProducto = (int) jTMostrarProductos.getValueAt(seleccionar, 0);
       // JOptionPane.showMessageDialog(null,"id rpducto es "+idProducto+" ", "idproducto " ,2);
       jTFNombreProductoActualizar.setText((String) jTMostrarProductos.getValueAt(seleccionar,1));
       preciocosto= (float) jTMostrarProductos.getValueAt(seleccionar, 3);
       jTFPrecioCostoActualizar.setText((Float.toString(preciocosto)));
       precioventa = (float) jTMostrarProductos.getValueAt(seleccionar, 4);
       jTFPrecioVentaActualizar.setText(Float.toString(precioventa));
       existencia = (int) jTMostrarProductos.getValueAt(seleccionar, 5);
       jTFExistenciaActualizar.setText(Integer.toString(existencia));
       String descripcion= (String) jTMostrarProductos.getValueAt(seleccionar, 2);
       jTFDescripcionProductoActualizar.setText(descripcion);
       
      // categoria cat = (categoria) jCBCategoriaProductoActualizar.getSelectedItem(); 
      // cat.setIdcategoria(1);
      // cat.setNombre("fasdlfkjasdf");
      
        
    }//GEN-LAST:event_jTMostrarProductosMouseClicked

    private void jBAceptarProductoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarProductoActualizarActionPerformed
        // TODO add your handling code here:
        
       PreparedStatement consulta;
        
       String nombreProducto = jTFNombreProductoActualizar.getText();
       float precioCosto = Float.parseFloat(jTFPrecioCostoActualizar.getText());
       float precioVenta = Float.parseFloat(jTFPrecioVentaActualizar.getText());
       String existenca = jTFExistenciaActualizar.getText();
       String descripcion = jTFDescripcionProductoActualizar.getText();
       
       categoria cat = (categoria) jCBCategoriaProductoActualizar.getSelectedItem();
       int categoria=  cat.getIdcategoria();
       
       
       try {
           String queryupdate;
            queryupdate = "UPDATE producto SET nombre = '"+nombreProducto+"',preciocosto='"+precioCosto+"',precioventa='"+precioVenta+"',existencia='"+existenca+"',descripcion='"+descripcion+"',categoria_idcategoria='"+categoria+"' WHERE idproducto='"+idProducto+"' ";
           
           consulta = conexion.getConection().prepareStatement(queryupdate);
           consulta.executeUpdate();
           
            jTFNombreProductoActualizar.setText("");
            jTFDescripcionProductoActualizar.setText("");
            jTFPrecioCostoActualizar.setText("");
            jTFPrecioVentaActualizar.setText("");
            jTFExistenciaActualizar.setText("");
            
            
            
             try {
            String query = "SELECT * FROM producto";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTMostrarProductos.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE","DESCRIPCION", "PRECIO COSTO", "PRECIO VENTEA","EXISTENCIA"});

            while (rs.next()){
             
                
                dfmproducto.addRow(new Object[] {rs.getInt("idproducto"),rs.getString("nombre"),rs.getString("descripcion"),rs.getFloat("preciocosto"),rs.getFloat("precioventa"),rs.getInt("existencia")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
           
           
       }catch(SQLException ex){
           
           System.out.println(ex.toString());
       }
        
    }//GEN-LAST:event_jBAceptarProductoActualizarActionPerformed

    private void jBCancelarProductoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarProductoActualizarActionPerformed
        // TODO add your handling code here:
        
            jTFNombreProductoActualizar.setText("");
            jTFDescripcionProductoActualizar.setText("");
            jTFPrecioCostoActualizar.setText("");
            jTFPrecioVentaActualizar.setText("");
            jTFExistenciaActualizar.setText("");
            
        
    }//GEN-LAST:event_jBCancelarProductoActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarProductoActualizar;
    private javax.swing.JButton jBCancelarProductoActualizar;
    private javax.swing.JComboBox<String> jCBCategoriaProductoActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTFDescripcionProductoActualizar;
    private javax.swing.JTextField jTFExistenciaActualizar;
    private javax.swing.JTextField jTFNombreProductoActualizar;
    private javax.swing.JTextField jTFPrecioCostoActualizar;
    private javax.swing.JTextField jTFPrecioVentaActualizar;
    private javax.swing.JTable jTMostrarProductos;
    // End of variables declaration//GEN-END:variables
}
