/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;
import packagemodelo.categoria;

/**
 *
 * @author Administrator
 */
public class JPBorrarProductos extends javax.swing.JPanel {

    /**
     * Creates new form JPBorrarProductos
     */
     PreparedStatement st;
     ResultSet rs;
     int idProducto;
     float preciocosto,precioventa;
     int existencia;
    
    public JPBorrarProductos() {
        initComponents();
        
        //categoria categorias = new categoria();
        // DefaultComboBoxModel modelocategoria = new DefaultComboBoxModel(categorias.mostrarCategorias());
        //jCBCategoriaProductoActualizar.setModel(modelocategoria);
        //MOSTRAR TABLA CON PRODUCTOS  
        try {
            String query = "SELECT * FROM producto";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTMostrarProductos.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE","DESCRIPCION", "PRECIO COSTO", "PRECIO VENTEA","EXISTENCIA"});

            while (rs.next()){
             
                
                dfmproducto.addRow(new Object[] {rs.getInt("idproducto"),rs.getString("nombre"),rs.getString("descripcion"),rs.getFloat("preciocosto"),rs.getFloat("precioventa"),rs.getInt("existencia")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFNombreProductoBorrar = new javax.swing.JTextField();
        jTFPrecioCostoBorrar = new javax.swing.JTextField();
        jTFPrecioVentaBorrar = new javax.swing.JTextField();
        jTFExistenciaBorrar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTFDescripcionProductoBorrar = new javax.swing.JTextArea();
        jBCancelarProductoBorrar = new javax.swing.JButton();
        jBAceptarProductoBorrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTMostrarProductos = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 260, 210));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("BORRAR PRODUCTOS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Precio costo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Precio venta");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Existencia");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Descripcion");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, -1, -1));

        jTFNombreProductoBorrar.setBackground(java.awt.Color.white);
        jTFNombreProductoBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreProductoBorrar.setForeground(java.awt.Color.black);
        add(jTFNombreProductoBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 210, 280, -1));

        jTFPrecioCostoBorrar.setBackground(java.awt.Color.white);
        jTFPrecioCostoBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFPrecioCostoBorrar.setForeground(java.awt.Color.black);
        add(jTFPrecioCostoBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 270, 280, -1));

        jTFPrecioVentaBorrar.setBackground(java.awt.Color.white);
        jTFPrecioVentaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFPrecioVentaBorrar.setForeground(java.awt.Color.black);
        add(jTFPrecioVentaBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 330, 280, -1));

        jTFExistenciaBorrar.setBackground(java.awt.Color.white);
        jTFExistenciaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFExistenciaBorrar.setForeground(java.awt.Color.black);
        add(jTFExistenciaBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 390, 280, -1));

        jScrollPane1.setForeground(java.awt.Color.white);

        jTFDescripcionProductoBorrar.setBackground(java.awt.Color.white);
        jTFDescripcionProductoBorrar.setColumns(20);
        jTFDescripcionProductoBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDescripcionProductoBorrar.setRows(5);
        jScrollPane1.setViewportView(jTFDescripcionProductoBorrar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 450, 280, 70));

        jBCancelarProductoBorrar.setBackground(java.awt.Color.red);
        jBCancelarProductoBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarProductoBorrar.setForeground(java.awt.Color.black);
        jBCancelarProductoBorrar.setText("Cancelar");
        jBCancelarProductoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarProductoBorrarActionPerformed(evt);
            }
        });
        add(jBCancelarProductoBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, -1, -1));

        jBAceptarProductoBorrar.setBackground(java.awt.Color.green);
        jBAceptarProductoBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarProductoBorrar.setForeground(java.awt.Color.black);
        jBAceptarProductoBorrar.setText("Aceptar");
        jBAceptarProductoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarProductoBorrarActionPerformed(evt);
            }
        });
        add(jBAceptarProductoBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 560, -1, -1));

        jTMostrarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio costo", "Precio venta", "Existencia", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTMostrarProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMostrarProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTMostrarProductos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 900, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarProductoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarProductoBorrarActionPerformed
        // TODO add your handling code here:
        
        
            jTFNombreProductoBorrar.setText("");
            jTFPrecioCostoBorrar.setText("");
            jTFPrecioVentaBorrar.setText("");
            jTFExistenciaBorrar.setText("");
            jTFDescripcionProductoBorrar.setText("");
            
    }//GEN-LAST:event_jBCancelarProductoBorrarActionPerformed

    private void jTMostrarProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMostrarProductosMouseClicked
        // TODO add your handling code here:

        int seleccionar = jTMostrarProductos.rowAtPoint(evt.getPoint());
        this.idProducto = (int) jTMostrarProductos.getValueAt(seleccionar, 0);
        // JOptionPane.showMessageDialog(null,"id rpducto es "+idProducto+" ", "idproducto " ,2);
        jTFNombreProductoBorrar.setText((String) jTMostrarProductos.getValueAt(seleccionar,1));
        preciocosto= (float) jTMostrarProductos.getValueAt(seleccionar, 3);
        jTFPrecioCostoBorrar.setText((Float.toString(preciocosto)));
        precioventa = (float) jTMostrarProductos.getValueAt(seleccionar, 4);
        jTFPrecioVentaBorrar.setText(Float.toString(precioventa));
        existencia = (int) jTMostrarProductos.getValueAt(seleccionar, 5);
        jTFExistenciaBorrar.setText(Integer.toString(existencia));
        String descripcion= (String) jTMostrarProductos.getValueAt(seleccionar, 2);
        jTFDescripcionProductoBorrar.setText(descripcion);

        

    }//GEN-LAST:event_jTMostrarProductosMouseClicked

    private void jBAceptarProductoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarProductoBorrarActionPerformed
        // TODO add your handling code here:
        
        
        PreparedStatement st;
        
        
        try {
            
            String queryborrar = "DELETE FROM producto WHERE idproducto ='"+idProducto+"'";
            st = conexion.getConection().prepareStatement(queryborrar);
            st.executeUpdate();
            JOptionPane.showMessageDialog(null,"El prducto se ha eliminado con exito", "!Atenciaon!",2);
            jTFNombreProductoBorrar.setText("");
            jTFPrecioCostoBorrar.setText("");
            jTFPrecioVentaBorrar.setText("");
            jTFExistenciaBorrar.setText("");
            jTFDescripcionProductoBorrar.setText("");
            
            
             //MOSTRAR TABLA CON PRODUCTOS  
        try {
            String query = "SELECT * FROM producto";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTMostrarProductos.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE","DESCRIPCION", "PRECIO COSTO", "PRECIO VENTEA","EXISTENCIA"});

            while (rs.next()){
             
                
                dfmproducto.addRow(new Object[] {rs.getInt("idproducto"),rs.getString("nombre"),rs.getString("descripcion"),rs.getFloat("preciocosto"),rs.getFloat("precioventa"),rs.getInt("existencia")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
            
            
            
        }catch (SQLException ex){
            
            System.out.println(ex.toString());
        }
        
        
    }//GEN-LAST:event_jBAceptarProductoBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarProductoBorrar;
    private javax.swing.JButton jBCancelarProductoBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTFDescripcionProductoBorrar;
    private javax.swing.JTextField jTFExistenciaBorrar;
    private javax.swing.JTextField jTFNombreProductoBorrar;
    private javax.swing.JTextField jTFPrecioCostoBorrar;
    private javax.swing.JTextField jTFPrecioVentaBorrar;
    private javax.swing.JTable jTMostrarProductos;
    // End of variables declaration//GEN-END:variables
}
