/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPCategorias extends javax.swing.JPanel {

    /**
     * Creates new form JPProducto
     */
    public JPCategorias() {
        initComponents();
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNombreCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionCategoria = new javax.swing.JTextArea();
        jBCancelarCategoria = new javax.swing.JButton();
        jBAceptarCategoria = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.black);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 260, 240));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Añadir Categoria");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Descripcion");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jTFNombreCategoria.setBackground(java.awt.Color.white);
        jTFNombreCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreCategoria.setForeground(java.awt.Color.black);
        add(jTFNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 280, -1));

        jTADescripcionCategoria.setBackground(java.awt.Color.white);
        jTADescripcionCategoria.setColumns(20);
        jTADescripcionCategoria.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTADescripcionCategoria.setForeground(java.awt.Color.black);
        jTADescripcionCategoria.setRows(5);
        jScrollPane1.setViewportView(jTADescripcionCategoria);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        jBCancelarCategoria.setBackground(java.awt.Color.red);
        jBCancelarCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarCategoria.setForeground(java.awt.Color.black);
        jBCancelarCategoria.setText("Cancelar");
        jBCancelarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarCategoriaActionPerformed(evt);
            }
        });
        add(jBCancelarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, -1));

        jBAceptarCategoria.setBackground(java.awt.Color.green);
        jBAceptarCategoria.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarCategoria.setForeground(java.awt.Color.black);
        jBAceptarCategoria.setText("Aceptar");
        jBAceptarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarCategoriaActionPerformed(evt);
            }
        });
        add(jBAceptarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarCategoriaActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement consulta;
        ResultSet resultado;
        
        String nombre = jTFNombreCategoria.getText();
        String descripcion = jTADescripcionCategoria.getText();
       //********************************************************
       //VALIDACION
        if (nombre.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre de la categoria","ERROR",2);
            
            
        }else if (descripcion.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la descripcion de la categoria","ERROR",2);
            
            
        }else {
            
             try {
            String query = "INSERT INTO categoria(nombre,descripcion) VALUES ('"+nombre+"','"+descripcion+"')";
            
            consulta = conexion.getConection().prepareStatement(query);
            consulta.executeUpdate();
            jTFNombreCategoria.setText("");
            jTADescripcionCategoria.setText("");
            
            
            
            }catch(SQLException excepcion){

                System.out.println(excepcion.toString());
            }
        }
        
       
        
        
    }//GEN-LAST:event_jBAceptarCategoriaActionPerformed

    private void jBCancelarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarCategoriaActionPerformed
        // TODO add your handling code here:
        
        jTFNombreCategoria.setText("");
        jTADescripcionCategoria.setText("");
    }//GEN-LAST:event_jBCancelarCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarCategoria;
    private javax.swing.JButton jBCancelarCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcionCategoria;
    private javax.swing.JTextField jTFNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
