/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import packageconexion.conexion;
import packagemodelo.categoria;

/**
 *
 * @author Administrator
 */
public class JPCrearProductos extends javax.swing.JPanel {

    /**
     * Creates new form JPGestionarProductos
     */
    public JPCrearProductos() {
        initComponents();
        categoria cc = new categoria();
        DefaultComboBoxModel modelocategoria = new DefaultComboBoxModel(cc.mostrarCategorias());
        
        jCBCategoriaProductoAgregar.setModel(modelocategoria);
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFNombreProductoCrear = new javax.swing.JTextField();
        jTFPrecioCostoCrear = new javax.swing.JTextField();
        jTFPrecioVentaCrear = new javax.swing.JTextField();
        jTFExistenciaCrear = new javax.swing.JTextField();
        jBCancelarProductoCrear = new javax.swing.JButton();
        jBAceptarProductoCrear = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jCBCategoriaProductoAgregar = new javax.swing.JComboBox<>();
        jTFDescripcionProductoCrear = new javax.swing.JTextField();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 0, 260, 210));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("CREAR PRODUCTOS");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Precio costo");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Precio venta");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Existencia");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Descripcion");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        jTFNombreProductoCrear.setBackground(java.awt.Color.white);
        jTFNombreProductoCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreProductoCrear.setForeground(java.awt.Color.black);
        add(jTFNombreProductoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 280, -1));

        jTFPrecioCostoCrear.setBackground(java.awt.Color.white);
        jTFPrecioCostoCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFPrecioCostoCrear.setForeground(java.awt.Color.black);
        add(jTFPrecioCostoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 280, -1));

        jTFPrecioVentaCrear.setBackground(java.awt.Color.white);
        jTFPrecioVentaCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFPrecioVentaCrear.setForeground(java.awt.Color.black);
        add(jTFPrecioVentaCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 280, -1));

        jTFExistenciaCrear.setBackground(java.awt.Color.white);
        jTFExistenciaCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFExistenciaCrear.setForeground(java.awt.Color.black);
        add(jTFExistenciaCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 280, -1));

        jBCancelarProductoCrear.setBackground(java.awt.Color.red);
        jBCancelarProductoCrear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarProductoCrear.setForeground(java.awt.Color.black);
        jBCancelarProductoCrear.setText("Cancelar");
        jBCancelarProductoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarProductoCrearActionPerformed(evt);
            }
        });
        add(jBCancelarProductoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, -1, -1));

        jBAceptarProductoCrear.setBackground(java.awt.Color.green);
        jBAceptarProductoCrear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarProductoCrear.setForeground(java.awt.Color.black);
        jBAceptarProductoCrear.setText("Aceptar");
        jBAceptarProductoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarProductoCrearActionPerformed(evt);
            }
        });
        add(jBAceptarProductoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Categoría");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 356, -1, 20));

        jCBCategoriaProductoAgregar.setBackground(java.awt.Color.white);
        jCBCategoriaProductoAgregar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCBCategoriaProductoAgregar.setForeground(java.awt.Color.black);
        jCBCategoriaProductoAgregar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jCBCategoriaProductoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 280, -1));

        jTFDescripcionProductoCrear.setBackground(java.awt.Color.white);
        jTFDescripcionProductoCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDescripcionProductoCrear.setForeground(java.awt.Color.black);
        add(jTFDescripcionProductoCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, 290, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarProductoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarProductoCrearActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement consulta;
        ResultSet resultado;
        
        String nombreProducto = jTFNombreProductoCrear.getText();
        String descripcionProducto= jTFDescripcionProductoCrear.getText();

       categoria cat = (categoria) jCBCategoriaProductoAgregar.getSelectedItem();
       int categoria=  cat.getIdcategoria();
       
      
     
        //VALIDACION
        ///******************************************************
        if ((nombreProducto.trim().equals(""))){
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre del producto ","ERROR",2);
        }else if((descripcionProducto.trim().equals(""))){
             JOptionPane.showMessageDialog(null, "Debe ingresar una descripcion del producto ","ERROR",2);
        } else if(jTFPrecioCostoCrear.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un  precio costo del producto ","ERROR",2);
        } else if (jTFPrecioVentaCrear.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar un  precio venta del producto ","ERROR",2);
        } else if (jTFExistenciaCrear.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la existencia del producto ","ERROR",2);
        } else if((categoria==0)){
             JOptionPane.showMessageDialog(null, "Debe ingresar una categoria del producto ","ERROR",2);
        }
        else if (categoria==0){
            JOptionPane.showMessageDialog(null, "Debe seleccionar una categoria ","ERROR",2);
        }
        //***************************************************************************
         else{ 
            float costoProducto = Float.parseFloat(jTFPrecioCostoCrear.getText());
            float costoVentaProducto= Float.parseFloat(jTFPrecioVentaCrear.getText());
            int existenciaProducto= Integer.parseInt(jTFExistenciaCrear.getText());
            
        try{
            
            String query= "INSERT INTO producto (nombre,descripcion,preciocosto,precioventa,existencia,categoria_idcategoria )"
                    + "VALUES('"+nombreProducto+"','"+descripcionProducto+"','"+costoProducto+"','"+costoVentaProducto+"','"+existenciaProducto+"','"+categoria+"')";
            
            consulta=conexion.getConection().prepareStatement(query);
            consulta.executeUpdate();
            
            jTFNombreProductoCrear.setText("");
            jTFDescripcionProductoCrear.setText("");
            jTFPrecioCostoCrear.setText("");
            jTFPrecioVentaCrear.setText("");
            jTFExistenciaCrear.setText("");
            
            
        } catch(SQLException ex){
            Logger.getLogger(JPLogin.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
        
   
  
     
      
    }//GEN-LAST:event_jBAceptarProductoCrearActionPerformed

    private void jBCancelarProductoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarProductoCrearActionPerformed
        // TODO add your handling code here:
            jTFNombreProductoCrear.setText("");
            jTFDescripcionProductoCrear.setText("");
            jTFPrecioCostoCrear.setText("");
            jTFPrecioVentaCrear.setText("");
            jTFExistenciaCrear.setText("");
    }//GEN-LAST:event_jBCancelarProductoCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarProductoCrear;
    private javax.swing.JButton jBCancelarProductoCrear;
    private javax.swing.JComboBox<String> jCBCategoriaProductoAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTFDescripcionProductoCrear;
    private javax.swing.JTextField jTFExistenciaCrear;
    private javax.swing.JTextField jTFNombreProductoCrear;
    private javax.swing.JTextField jTFPrecioCostoCrear;
    private javax.swing.JTextField jTFPrecioVentaCrear;
    // End of variables declaration//GEN-END:variables
}
