/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPCrearProveedores extends javax.swing.JPanel {

    /**
     * Creates new form JPProveedores
     */
    public JPCrearProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNombreEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombrevendedor = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFDireccionProveedor = new javax.swing.JTextField();
        jTFNitProvedor = new javax.swing.JTextField();
        jTFTelefonoProveedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionProveedor = new javax.swing.JTextArea();
        jTFNombreVendedor = new javax.swing.JTextField();
        JBCancelarProveedor = new javax.swing.JButton();
        jTFTelefonoVendedor = new javax.swing.JTextField();
        jBHechoPRoveedor = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 190));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Crear Proveedor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre empresa");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, 20));

        jTFNombreEmpresa.setBackground(java.awt.Color.white);
        jTFNombreEmpresa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreEmpresa.setForeground(java.awt.Color.black);
        jTFNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreEmpresaActionPerformed(evt);
            }
        });
        add(jTFNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 260, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Direccion");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("NIT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Descripcion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Telefono");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        nombrevendedor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nombrevendedor.setForeground(java.awt.Color.black);
        nombrevendedor.setText("Nombre vendedor");
        add(nombrevendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Telefono vendedor");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, -1, -1));

        jTFDireccionProveedor.setBackground(java.awt.Color.white);
        jTFDireccionProveedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDireccionProveedorActionPerformed(evt);
            }
        });
        add(jTFDireccionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 260, -1));

        jTFNitProvedor.setBackground(java.awt.Color.white);
        jTFNitProvedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jTFNitProvedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, -1));

        jTFTelefonoProveedor.setBackground(java.awt.Color.white);
        jTFTelefonoProveedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jTFTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 200, -1));

        jTADescripcionProveedor.setBackground(java.awt.Color.white);
        jTADescripcionProveedor.setColumns(20);
        jTADescripcionProveedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTADescripcionProveedor.setRows(5);
        jScrollPane1.setViewportView(jTADescripcionProveedor);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 370, 90));

        jTFNombreVendedor.setBackground(java.awt.Color.white);
        jTFNombreVendedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jTFNombreVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 210, -1));

        JBCancelarProveedor.setBackground(java.awt.Color.red);
        JBCancelarProveedor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBCancelarProveedor.setForeground(java.awt.Color.black);
        JBCancelarProveedor.setText("Cancelar");
        JBCancelarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarProveedorActionPerformed(evt);
            }
        });
        add(JBCancelarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 160, 50));

        jTFTelefonoVendedor.setBackground(java.awt.Color.white);
        jTFTelefonoVendedor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        add(jTFTelefonoVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 220, -1));

        jBHechoPRoveedor.setBackground(java.awt.Color.green);
        jBHechoPRoveedor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBHechoPRoveedor.setForeground(java.awt.Color.black);
        jBHechoPRoveedor.setText("Hecho");
        jBHechoPRoveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHechoPRoveedorActionPerformed(evt);
            }
        });
        add(jBHechoPRoveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 180, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreEmpresaActionPerformed

    private void jTFDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDireccionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDireccionProveedorActionPerformed

    private void jBHechoPRoveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHechoPRoveedorActionPerformed
        // TODO add your handling code here:
        PreparedStatement consulta;
        ResultSet resultado;
        
        String nombreEmpresa= jTFNombreEmpresa.getText();
        String direccion = jTFDireccionProveedor.getText();
        String nitempresa = jTFNitProvedor.getText();
        String telefonoEmpresa = jTFTelefonoProveedor.getText();
        String nombreVendedor = jTFNombreVendedor.getText();
        String telefonoVendedor = jTFTelefonoVendedor.getText();
        String descripcion = jTADescripcionProveedor.getText();
        //VALIDACION
        ///******************************************************
        if ((nombreEmpresa.trim().equals(""))){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre de la empresa ","ERROR",2);
        }else if(direccion.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar la direccion de la empresa","ERROR",2);
        } else if (nitempresa.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el NIT de la empresa","ERROR",2);
        } else if (telefonoEmpresa.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el telefono de la empresa","ERROR",2);
        } else if (nombreVendedor.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del vendedor","ERROR",2);
        } else if (telefonoVendedor.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el telefono del vendedor","ERROR",2);
        } else if (descripcion.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la descripcion de la empresa","ERROR",2);
        }
        //**********************************************************************************
         try {
             String query = "INSERT INTO proveedor (nombreempresa,direccion,nit,telefono,descripcion,vendedor,telefonovendedor) "
                     + "VALUES ('"+nombreEmpresa+"','"+direccion+"','"+nitempresa+"','"+telefonoEmpresa+"','"+descripcion+"','"+nombreVendedor+"','"+telefonoVendedor+"')";
             
             consulta=conexion.getConection().prepareStatement(query);
            consulta.executeUpdate();
            jTFNombreEmpresa.setText("");
            jTFDireccionProveedor.setText("");
            jTFNitProvedor.setText("");
            jTFTelefonoProveedor.setText("");
            jTFNombreVendedor.setText("");
            jTFTelefonoVendedor.setText("");
            jTADescripcionProveedor.setText("");
            
         }catch(SQLException ex){
             
            System.out.println(ex.toString());
         }
         
         
       
        
                        
        
    }//GEN-LAST:event_jBHechoPRoveedorActionPerformed

    private void JBCancelarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarProveedorActionPerformed
        // TODO add your handling code here:
        
            jTFNombreEmpresa.setText("");
            jTFDireccionProveedor.setText("");
            jTFNitProvedor.setText("");
            jTFTelefonoProveedor.setText("");
            jTFNombreVendedor.setText("");
            jTFTelefonoVendedor.setText("");
            jTADescripcionProveedor.setText("");
    }//GEN-LAST:event_JBCancelarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBCancelarProveedor;
    private javax.swing.JButton jBHechoPRoveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcionProveedor;
    private javax.swing.JTextField jTFDireccionProveedor;
    private javax.swing.JTextField jTFNitProvedor;
    private javax.swing.JTextField jTFNombreEmpresa;
    private javax.swing.JTextField jTFNombreVendedor;
    private javax.swing.JTextField jTFTelefonoProveedor;
    private javax.swing.JTextField jTFTelefonoVendedor;
    private javax.swing.JLabel nombrevendedor;
    // End of variables declaration//GEN-END:variables
}
