/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPCrearClientes extends javax.swing.JPanel {

    /**
     * Creates new form JPGestionarClientes
     */
    public JPCrearClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFApellidoCliente = new javax.swing.JTextField();
        jTFNitCliente = new javax.swing.JTextField();
        jTFDireccionCliente = new javax.swing.JTextField();
        jTFTelefonoCliente = new javax.swing.JTextField();
        jBCancelarCliente = new javax.swing.JButton();
        jBHechoCliente = new javax.swing.JButton();
        jTFNombreCliente = new javax.swing.JTextField();

        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.black);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("CREAR CLIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 300, 260));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("NIT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Direccion");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Telefono");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, -1, -1));

        jTFApellidoCliente.setBackground(java.awt.Color.white);
        jTFApellidoCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFApellidoCliente.setForeground(java.awt.Color.black);
        add(jTFApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 300, 40));

        jTFNitCliente.setBackground(java.awt.Color.white);
        jTFNitCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNitCliente.setForeground(java.awt.Color.black);
        add(jTFNitCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 300, 40));

        jTFDireccionCliente.setBackground(java.awt.Color.white);
        jTFDireccionCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDireccionCliente.setForeground(java.awt.Color.black);
        add(jTFDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 370, 40));

        jTFTelefonoCliente.setBackground(java.awt.Color.white);
        jTFTelefonoCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoCliente.setForeground(java.awt.Color.black);
        add(jTFTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 370, 40));

        jBCancelarCliente.setBackground(java.awt.Color.red);
        jBCancelarCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBCancelarCliente.setForeground(java.awt.Color.black);
        jBCancelarCliente.setText("Cancelar");
        jBCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarClienteActionPerformed(evt);
            }
        });
        add(jBCancelarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 170, 70));

        jBHechoCliente.setBackground(java.awt.Color.green);
        jBHechoCliente.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBHechoCliente.setForeground(java.awt.Color.black);
        jBHechoCliente.setText("Hecho");
        jBHechoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHechoClienteActionPerformed(evt);
            }
        });
        add(jBHechoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 170, 70));

        jTFNombreCliente.setBackground(java.awt.Color.white);
        jTFNombreCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreCliente.setForeground(java.awt.Color.black);
        add(jTFNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 300, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jBHechoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHechoClienteActionPerformed
        // TODO add your handling code here:
        
        
        PreparedStatement consulta;
        ResultSet resultado;
        
        String nombreCliente = jTFNombreCliente.getText();
        String apellidoCliente = jTFApellidoCliente.getText();
        String nitCliente = jTFNitCliente.getText();
        String direccionCliente = jTFDireccionCliente.getText();
        String telefonoCliente = jTFTelefonoCliente.getText();
        
        //VALIDACION
        //**************************************************************************************************
        if (nombreCliente.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del cliente ","ERROR",2);
            
        }else if (apellidoCliente.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar el apellido del cliente","ERROR",2);            
        } else if (nitCliente.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe ingresar  el NIT del cliente ","ERROR",2);
            
        } else if (direccionCliente.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la direccion del cliente","ERROR",2);
            
        } else if (telefonoCliente.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe ingresar el telefono del cliente","ERROR",2);
        } 
        
        //***********************************************************************************************************
        else {
            
            try {
                
               String  query = "INSERT INTO cliente(nombre,apellido,nit,direccion,telefono) VALUES ('"+nombreCliente+"','"+apellidoCliente+"','"+nitCliente+"','"+direccionCliente+"','"+telefonoCliente+"')";
                
               consulta= conexion.getConection().prepareStatement(query);
               
               consulta.executeUpdate();
               jTFNombreCliente.setText("");
               jTFApellidoCliente.setText("");
               jTFNitCliente.setText("");
               jTFDireccionCliente.setText("");
               jTFTelefonoCliente.setText("");
               
                
                
            }catch(SQLException ex){
                
                       System.out.println(ex.toString());
                
                
            }
        }
        
        
    }//GEN-LAST:event_jBHechoClienteActionPerformed

    private void jBCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarClienteActionPerformed
        // TODO add your handling code here:
                jTFNombreCliente.setText("");
               jTFApellidoCliente.setText("");
               jTFNitCliente.setText("");
               jTFDireccionCliente.setText("");
               jTFTelefonoCliente.setText("");
        
    }//GEN-LAST:event_jBCancelarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelarCliente;
    private javax.swing.JButton jBHechoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFApellidoCliente;
    private javax.swing.JTextField jTFDireccionCliente;
    private javax.swing.JTextField jTFNitCliente;
    private javax.swing.JTextField jTFNombreCliente;
    private javax.swing.JTextField jTFTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
