/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import packageconexion.conexion;
import packagemodelo.rolusuario;

/**
 *
 * @author Administrator
 */
public class JPCrearUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form JPGestionUsuarios
     */
    public JPCrearUsuarios() {
        initComponents();
        
        //Mostrar Roles en el combobox
        rolusuario roles= new rolusuario();
        DefaultComboBoxModel modelorol = new DefaultComboBoxModel(roles.mostrarRoles());
        jCBRolUsuario.setModel(modelorol);
        //***********************************************
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTTNombreUsuarioCrear = new javax.swing.JTextField();
        jTFApellidoUsuarioCrear = new javax.swing.JTextField();
        jTFDireccionUsuarioCrear = new javax.swing.JTextField();
        jTFTelefonoUsuarioCrear = new javax.swing.JTextField();
        jTFCargoUsuarioCrear = new javax.swing.JTextField();
        jTFUsuarioUsuarioCrear = new javax.swing.JTextField();
        jTFContraseniaaUsuarioCrear = new javax.swing.JTextField();
        jTFCorreoUsuarioCrear = new javax.swing.JTextField();
        jTFCuiUsuarioCrear = new javax.swing.JTextField();
        jBCancelarUsuariosCrear = new javax.swing.JButton();
        jBAceptarUsuariosCrear = new javax.swing.JButton();
        jCBRolUsuario = new javax.swing.JComboBox<>();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Crear Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, -10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Apellido");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Direccion");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Telefono ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Cargo");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Usuario");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Contraseña");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Correo electronico");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.black);
        jLabel11.setText("CUI");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Rol");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, -1, -1));

        jTTNombreUsuarioCrear.setBackground(java.awt.Color.white);
        jTTNombreUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTTNombreUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTTNombreUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 300, 30));

        jTFApellidoUsuarioCrear.setBackground(java.awt.Color.white);
        jTFApellidoUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFApellidoUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFApellidoUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 300, -1));

        jTFDireccionUsuarioCrear.setBackground(java.awt.Color.white);
        jTFDireccionUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDireccionUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFDireccionUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 300, -1));

        jTFTelefonoUsuarioCrear.setBackground(java.awt.Color.white);
        jTFTelefonoUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFTelefonoUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 300, -1));

        jTFCargoUsuarioCrear.setBackground(java.awt.Color.white);
        jTFCargoUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFCargoUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFCargoUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 300, -1));

        jTFUsuarioUsuarioCrear.setBackground(java.awt.Color.white);
        jTFUsuarioUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFUsuarioUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFUsuarioUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 280, -1));

        jTFContraseniaaUsuarioCrear.setBackground(java.awt.Color.white);
        jTFContraseniaaUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFContraseniaaUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFContraseniaaUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 290, -1));

        jTFCorreoUsuarioCrear.setBackground(java.awt.Color.white);
        jTFCorreoUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFCorreoUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFCorreoUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 290, -1));

        jTFCuiUsuarioCrear.setBackground(java.awt.Color.white);
        jTFCuiUsuarioCrear.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFCuiUsuarioCrear.setForeground(java.awt.Color.black);
        add(jTFCuiUsuarioCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 300, -1));

        jBCancelarUsuariosCrear.setBackground(java.awt.Color.red);
        jBCancelarUsuariosCrear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarUsuariosCrear.setForeground(java.awt.Color.black);
        jBCancelarUsuariosCrear.setText("Cancelar");
        jBCancelarUsuariosCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarUsuariosCrearActionPerformed(evt);
            }
        });
        add(jBCancelarUsuariosCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jBAceptarUsuariosCrear.setBackground(java.awt.Color.green);
        jBAceptarUsuariosCrear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarUsuariosCrear.setForeground(java.awt.Color.black);
        jBAceptarUsuariosCrear.setText("Aceptar");
        jBAceptarUsuariosCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarUsuariosCrearActionPerformed(evt);
            }
        });
        add(jBAceptarUsuariosCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        jCBRolUsuario.setBackground(java.awt.Color.white);
        jCBRolUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jCBRolUsuario.setForeground(java.awt.Color.black);
        jCBRolUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jCBRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 300, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarUsuariosCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarUsuariosCrearActionPerformed
        // TODO add your handling code here:
        
        PreparedStatement consulta;
        ResultSet resultado;
        
        String nombreUsuario = jTTNombreUsuarioCrear.getText();
        String apellidoUsuario = jTFApellidoUsuarioCrear.getText();
        String direccionUsuario = jTFDireccionUsuarioCrear.getText();
        String telefonoUsuario = jTFTelefonoUsuarioCrear.getText();
        String cargoUsuario = jTFCargoUsuarioCrear.getText();
        String usuario= jTFUsuarioUsuarioCrear.getText();
        String contrasenia = jTFContraseniaaUsuarioCrear.getText();
        String correo = jTFCorreoUsuarioCrear.getText();
        String cui = jTFCuiUsuarioCrear.getText();
        
        
        rolusuario rol = (rolusuario) jCBRolUsuario.getSelectedItem();
        int rolseleccionado=  rol.getIdrol();
        
        //VALLIDACION
        //********************************************************************************
        if (nombreUsuario.trim().equals("")){
             JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del usuario ","ERROR",2);
            
        }else if (apellidoUsuario.trim().equals("")){
            
             JOptionPane.showMessageDialog(null, "Debe ingresar el apellido del usuario ","ERROR",2);
        } else if (direccionUsuario.trim().equals("")){
              JOptionPane.showMessageDialog(null, "Debe ingresar la direccion del usuario ","ERROR",2);
            
        }else if (telefonoUsuario.trim().equals("")){
              JOptionPane.showMessageDialog(null, "Debe ingresar el telefono del usuario ","ERROR",2);
            
        } else if (cargoUsuario.trim().equals("")){
            
              JOptionPane.showMessageDialog(null, "Debe ingresar el cargo del usuario ","ERROR",2);
        }else if (usuario.trim().equals("")){
              JOptionPane.showMessageDialog(null, "Debe ingresar un nombre de usuario ","ERROR",2);
        }//agregar mas validaciones a la contraseña
        else if (contrasenia.trim().equals("")){
              JOptionPane.showMessageDialog(null, "Debe ingresar una contraseña ","ERROR",2);
        }//agragar mas validaciones al correo
        else if (correo.trim().equals("")){
              JOptionPane.showMessageDialog(null, "Debe ingresar un correo valido","ERROR",2);
        }else if (cui.trim().equals("")){
              JOptionPane.showMessageDialog(null, "Debe ingresar el CUI del usuario ","ERROR",2);
        }
        //**********************************************************************************************
        else {
            try {
              String query="INSERT INTO usuario (nombre,apellido,direccion,telefono,cargo,usuario,contrasenia,correoelectronico,cui,rol_idrol) "
                      + "VALUES ('"+nombreUsuario+"','"+apellidoUsuario+"','"+direccionUsuario+"','"+telefonoUsuario+"','"+cargoUsuario+"','"+usuario+"','"+contrasenia+"','"+correo+"','"+cui+"','"+rolseleccionado+"')";
                
             consulta = conexion.getConection().prepareStatement(query);
             consulta.executeUpdate();
             
            jTTNombreUsuarioCrear.setText("");
            jTFApellidoUsuarioCrear.setText("");
            jTFDireccionUsuarioCrear.setText("");
            jTFTelefonoUsuarioCrear.setText("");
            jTFCargoUsuarioCrear.setText("");
            jTFUsuarioUsuarioCrear.setText("");
            jTFContraseniaaUsuarioCrear.setText("");
            jTFCorreoUsuarioCrear.setText("");
            jTFCuiUsuarioCrear.setText("");
             
              
            }catch(SQLException ex){
                System.out.println(ex.toString());
            }
            
        }
        
        
    }//GEN-LAST:event_jBAceptarUsuariosCrearActionPerformed

    private void jBCancelarUsuariosCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarUsuariosCrearActionPerformed
        // TODO add your handling code here:
        
            jTTNombreUsuarioCrear.setText("");
            jTFApellidoUsuarioCrear.setText("");
            jTFDireccionUsuarioCrear.setText("");
            jTFTelefonoUsuarioCrear.setText("");
            jTFCargoUsuarioCrear.setText("");
            jTFUsuarioUsuarioCrear.setText("");
            jTFContraseniaaUsuarioCrear.setText("");
            jTFCorreoUsuarioCrear.setText("");
            jTFCuiUsuarioCrear.setText("");
    }//GEN-LAST:event_jBCancelarUsuariosCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarUsuariosCrear;
    private javax.swing.JButton jBCancelarUsuariosCrear;
    private javax.swing.JComboBox<String> jCBRolUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTFApellidoUsuarioCrear;
    private javax.swing.JTextField jTFCargoUsuarioCrear;
    private javax.swing.JTextField jTFContraseniaaUsuarioCrear;
    private javax.swing.JTextField jTFCorreoUsuarioCrear;
    private javax.swing.JTextField jTFCuiUsuarioCrear;
    private javax.swing.JTextField jTFDireccionUsuarioCrear;
    private javax.swing.JTextField jTFTelefonoUsuarioCrear;
    private javax.swing.JTextField jTFUsuarioUsuarioCrear;
    private javax.swing.JTextField jTTNombreUsuarioCrear;
    // End of variables declaration//GEN-END:variables
}
