/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPListaProveedoresImprimir extends javax.swing.JPanel {

    /**
     * Creates new form JPListaProveedores
     */
    PreparedStatement st;
    ResultSet rs;
    public JPListaProveedoresImprimir() {
        initComponents();
        
        
          try {
            String query = "SELECT * FROM proveedor";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            JTListaProveedores.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE EMRPRESA","DIRECCION", "NIT", "TELEFONO","DESCRIPCION","VENDEDOR","TELEFONO VENDEDOR"});

            while (rs.next()){
             
                dfmproducto.addRow(new Object[] {rs.getInt("idproveedor"),rs.getString("nombreempresa"),rs.getString("direccion"),rs.getString("nit"),rs.getString("telefono"),rs.getString("descripcion"),rs.getString("vendedor"),rs.getString("telefonovendedor")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBImprimirListado = new javax.swing.JButton();
        JBImrpmirProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTListaProveedores = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(java.awt.Color.black);
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("LISTA DE PROVEEDORES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 0, 240, 200));

        JBImprimirListado.setBackground(java.awt.Color.blue);
        JBImprimirListado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBImprimirListado.setForeground(java.awt.Color.black);
        JBImprimirListado.setText("Imprimir Listado");
        add(JBImprimirListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 280, 50));

        JBImrpmirProveedor.setBackground(java.awt.Color.orange);
        JBImrpmirProveedor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBImrpmirProveedor.setForeground(java.awt.Color.black);
        JBImrpmirProveedor.setText("Imprimir Proveedor");
        JBImrpmirProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(JBImrpmirProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 330, 280, 50));

        JTListaProveedores.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        JTListaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "IDProveedor", "Nombre Empresa", "Direccion", "NIT", "Telefono", "Nombre Vendedor", "Telefono Vendedor", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTListaProveedores);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 900, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBImprimirListado;
    private javax.swing.JButton JBImrpmirProveedor;
    private javax.swing.JTable JTListaProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
