/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */



public class JPListadoProductosImprimir extends javax.swing.JPanel {

    /**
     * Creates new form JPListadoProductos
     */
    
    PreparedStatement st;
    ResultSet rs;
    
    public JPListadoProductosImprimir() {
        initComponents();
        
        
        try {
            String query = "SELECT * FROM producto";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTMostrarProductos.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE","DESCRIPCION", "PRECIO COSTO", "PRECIO VENTEA","EXISTENCIA"});

            while (rs.next()){
             
                
                dfmproducto.addRow(new Object[] {rs.getInt("idproducto"),rs.getString("nombre"),rs.getString("descripcion"),rs.getFloat("preciocosto"),rs.getFloat("precioventa"),rs.getInt("existencia")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
            
            
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMostrarProductos = new javax.swing.JTable();
        JBImprimirListado = new javax.swing.JButton();
        JBImprimirDatosCliente = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Listado Productos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jTMostrarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio costo", "Precio venta", "Existencia", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTMostrarProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 970, 480));

        JBImprimirListado.setBackground(java.awt.Color.blue);
        JBImprimirListado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBImprimirListado.setForeground(java.awt.Color.black);
        JBImprimirListado.setText("Imprimir Listado");
        add(JBImprimirListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 320, 230, 40));

        JBImprimirDatosCliente.setBackground(java.awt.Color.orange);
        JBImprimirDatosCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBImprimirDatosCliente.setForeground(java.awt.Color.black);
        JBImprimirDatosCliente.setText("Imprimir datos cliente");
        add(JBImprimirDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, 230, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBImprimirDatosCliente;
    private javax.swing.JButton JBImprimirListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMostrarProductos;
    // End of variables declaration//GEN-END:variables
}
