/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPListadoClientesImprimir extends javax.swing.JPanel {

    /**
     * Creates new form JPListadoClientes
     */
    
    PreparedStatement st;
    ResultSet rs;
    public JPListadoClientesImprimir() {
        initComponents();
        
        try {
            String query = "SELECT * FROM cliente";
            
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmcliente = new DefaultTableModel();
            
            jTListadoClientes.setModel(dfmcliente);
            dfmcliente.setColumnIdentifiers(new Object[] {"ID","NOMBRE","APELLIDO", "NIT", "DIRECCION","TELEFONO"});

            while (rs.next()){
             
                
                dfmcliente.addRow(new Object[] {rs.getInt("idcliente"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("nit"),rs.getString("direccion"),rs.getString("telefono")});
            }
            
            
            
        }catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBImprimirListado = new javax.swing.JButton();
        JBImprimirDatosCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTListadoClientes = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("LISTADO DE CLIENTES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 260, 210));

        JBImprimirListado.setBackground(java.awt.Color.blue);
        JBImprimirListado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBImprimirListado.setForeground(java.awt.Color.black);
        JBImprimirListado.setText("Imprimir Listado");
        add(JBImprimirListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 300, 230, 40));

        JBImprimirDatosCliente.setBackground(java.awt.Color.orange);
        JBImprimirDatosCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBImprimirDatosCliente.setForeground(java.awt.Color.black);
        JBImprimirDatosCliente.setText("Imprimir datos cliente");
        add(JBImprimirDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 350, 230, 40));

        jTListadoClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "NIT", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTListadoClientes);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 930, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBImprimirDatosCliente;
    private javax.swing.JButton JBImprimirListado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTListadoClientes;
    // End of variables declaration//GEN-END:variables
}
