/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPListadoUsuariosImprimir extends javax.swing.JPanel {

    /**
     * Creates new form JPListadousuarios
     */
    
    
    
    PreparedStatement st;
    ResultSet rs;
    public JPListadoUsuariosImprimir() {
        initComponents();
        
        
        try {
            String query="SELECT * FROM usuario";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmusuarios = new DefaultTableModel();
            
            
            jTUsuarios.setModel(dfmusuarios);
            
            dfmusuarios.setColumnIdentifiers(new Object[] {"ID","NOMBRE","APELLIDO","DIRECCION","TELEFONO","CARGO","USUARIO","CONTRASEÑA","CORREO ELECTRONICO","CUI"});
            
            while(rs.next()){
                
                dfmusuarios.addRow(new Object[] {rs.getInt("idusuario"),rs.getString("nombre"),rs.getString("apellido"),rs.getString("direccion"),rs.getString("telefono"),rs.getString("cargo"),rs.getString("usuario"),rs.getString("contrasenia"),rs.getString("correoelectronico"),rs.getString("cui")});
                
            }
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBImprimirLista = new javax.swing.JButton();
        jBImprimirUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTUsuarios = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 30, -1, 220));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Listado de Usuarios");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jBImprimirLista.setBackground(java.awt.Color.blue);
        jBImprimirLista.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBImprimirLista.setForeground(java.awt.Color.black);
        jBImprimirLista.setText("Imprimir Lista");
        add(jBImprimirLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 290, 180, -1));

        jBImprimirUsuario.setBackground(java.awt.Color.orange);
        jBImprimirUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBImprimirUsuario.setForeground(java.awt.Color.black);
        jBImprimirUsuario.setText("Imprimir Usuario");
        add(jBImprimirUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 340, 180, -1));

        jTUsuarios.setBackground(java.awt.Color.white);
        jTUsuarios.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTUsuarios.setForeground(java.awt.Color.black);
        jTUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Title 3", "Telefono", "Cargo", "Usuario", "Contraseña", "Correo electronico", "CUI", " Rol"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1070, 440));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBImprimirLista;
    private javax.swing.JButton jBImprimirUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTUsuarios;
    // End of variables declaration//GEN-END:variables
}
