/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPLogin extends javax.swing.JPanel {
    

    public JPLogin() {
        initComponents();
       
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFusuario = new javax.swing.JTextField();
        jPFcontrasenia = new javax.swing.JPasswordField();
        jBingresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("INICIAR SESION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 190, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("USUARIO");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 90, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("CONTRASEÑA");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 130, 30));

        jTFusuario.setBackground(java.awt.Color.white);
        add(jTFusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 180, 30));

        jPFcontrasenia.setBackground(java.awt.Color.white);
        add(jPFcontrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 180, 30));

        jBingresar.setBackground(java.awt.Color.green);
        jBingresar.setForeground(java.awt.Color.black);
        jBingresar.setText("INGRESAR");
        jBingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBingresarActionPerformed(evt);
            }
        });
        add(jBingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 110, 50));

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Ferreteria RASH");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 190, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/1.jpg"))); // NOI18N
        fondo.setText("jLabel4");
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void jBingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBingresarActionPerformed

        //*******************************
        String nombreusuario = jTFusuario.getText();
        
        String contrasenia= String.valueOf(jPFcontrasenia.getPassword());
        //VERIFICAR USUARIO CONTRASEÑA
        //consulta SQL
        PreparedStatement consulta;
        ResultSet resultado;
        //***************************
        if (nombreusuario.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe escribir un nombre de usuario","ERROR",2);
        }else if (contrasenia.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe esecriir una contraseña ","ERROR",2);
            
        }
        //*********************************************************************
        else{
            
            try{
                
                consulta=conexion.getConection().prepareStatement("SELECT*FROM usuario WHERE usuario= '"+nombreusuario+"'AND contrasenia='"+contrasenia+"'");
                resultado= consulta.executeQuery();
                
                if (resultado.next()){
                    
                    JOptionPane.showMessageDialog(null, "Acceso correcto", "Info",2);
                    MarcoLogin marcologin = (MarcoLogin) SwingUtilities.getWindowAncestor(this);
                    marcologin.dispose();
                    JFPrincipal marcomenu = new JFPrincipal();
                    marcomenu.setVisible(true);
                   
                                      
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrecto", "Info",2);
                }
               
                
            }
            catch(SQLException ex){

                Logger.getLogger(JPLogin.class.getName()).log(Level.SEVERE,null,ex);
                
                
            }
      
     
    }//GEN-LAST:event_jBingresarActionPerformed

 }   
   private int iduser = 1;
    
    public int getIduser() {
        return iduser;
    }

    public void setIduser(int iduser) {
        this.iduser = iduser;
    }
    
   
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jBingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPFcontrasenia;
    private javax.swing.JTextField jTFusuario;
    // End of variables declaration//GEN-END:variables

     
}
