/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;


import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class JPMenu extends javax.swing.JPanel {

    /**
     * Creates new form JPMenu
     */
    public JPMenu() {
        initComponents();
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBClientes = new javax.swing.JButton();
        jBProveedores = new javax.swing.JButton();
        jBUsuarios = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        jBMetodoPago = new javax.swing.JButton();
        jBFacturacion = new javax.swing.JButton();
        jBRol = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(java.awt.Color.darkGray);
        setPreferredSize(new java.awt.Dimension(740, 300));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBClientes.setBackground(java.awt.Color.cyan);
        jBClientes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBClientes.setForeground(java.awt.Color.white);
        jBClientes.setText("Clientes");
        jBClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBClientesMouseClicked(evt);
            }
        });
        jBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClientesActionPerformed(evt);
            }
        });
        add(jBClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 50));

        jBProveedores.setBackground(java.awt.Color.cyan);
        jBProveedores.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBProveedores.setForeground(java.awt.Color.white);
        jBProveedores.setText("Proveedores");
        add(jBProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 150, 50));

        jBUsuarios.setBackground(java.awt.Color.cyan);
        jBUsuarios.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jBUsuarios.setForeground(java.awt.Color.white);
        jBUsuarios.setText("Usuarios");
        add(jBUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 140, 50));

        menu.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        menu.setForeground(java.awt.Color.white);
        menu.setText("MENU");
        add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 80, 30));

        jBMetodoPago.setBackground(java.awt.Color.cyan);
        jBMetodoPago.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBMetodoPago.setForeground(java.awt.Color.white);
        jBMetodoPago.setText("Agregar Metodo de Pago");
        jBMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMetodoPagoActionPerformed(evt);
            }
        });
        add(jBMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 260, 60));

        jBFacturacion.setBackground(java.awt.Color.cyan);
        jBFacturacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBFacturacion.setForeground(java.awt.Color.white);
        jBFacturacion.setText("Facturacion");
        add(jBFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 150, 60));

        jBRol.setBackground(java.awt.Color.cyan);
        jBRol.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBRol.setForeground(java.awt.Color.white);
        jBRol.setText("Agregar Rol");
        add(jBRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 150, 60));

        fondo.setBackground(java.awt.Color.cyan);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/1.jpg"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 800, 440));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("BIENVENIDO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jBMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBMetodoPagoActionPerformed

    private void jBClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBClientesActionPerformed

    private void jBClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBClientesMouseClicked
         
          
    }//GEN-LAST:event_jBClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jBClientes;
    private javax.swing.JButton jBFacturacion;
    private javax.swing.JButton jBMetodoPago;
    private javax.swing.JButton jBProveedores;
    private javax.swing.JButton jBRol;
    private javax.swing.JButton jBUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menu;
    // End of variables declaration//GEN-END:variables
}
