/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPProveedoresActualizar extends javax.swing.JPanel {

    /**
     * Creates new form JPListaProveedoresActualizar
     */
    
    PreparedStatement st;
    ResultSet rs;
    int idProveedor;
    
    public JPProveedoresActualizar() {
        initComponents();
        
        try {
            String query = "SELECT * FROM proveedor";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTProveedores.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE EMRPRESA","DIRECCION", "NIT", "TELEFONO","DESCRIPCION","VENDEDOR","TELEFONO VENDEDOR"});

            while (rs.next()){
             
                dfmproducto.addRow(new Object[] {rs.getInt("idproveedor"),rs.getString("nombreempresa"),rs.getString("direccion"),rs.getString("nit"),rs.getString("telefono"),rs.getString("descripcion"),rs.getString("vendedor"),rs.getString("telefonovendedor")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombreEmpresaActualizar = new javax.swing.JTextField();
        jTFDIreccionEmpresaActualizar = new javax.swing.JTextField();
        jTFNitEmpresaActualizar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFTelefonoEmpresaActualizar = new javax.swing.JTextField();
        jTFVendedorActualizar = new javax.swing.JTextField();
        jTFTelefonoVendedorActualizar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionEmpresaActualizar = new javax.swing.JTextArea();
        jBCancelarActualizar = new javax.swing.JButton();
        jBAceptarActualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProveedores = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("ACTUALIZAR PROVEEDOR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre Empresa");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Direccion");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("NIT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jTFNombreEmpresaActualizar.setBackground(java.awt.Color.white);
        jTFNombreEmpresaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreEmpresaActualizar.setForeground(java.awt.Color.black);
        add(jTFNombreEmpresaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 340, -1));

        jTFDIreccionEmpresaActualizar.setBackground(java.awt.Color.white);
        jTFDIreccionEmpresaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDIreccionEmpresaActualizar.setForeground(java.awt.Color.black);
        add(jTFDIreccionEmpresaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 340, -1));

        jTFNitEmpresaActualizar.setBackground(java.awt.Color.white);
        jTFNitEmpresaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNitEmpresaActualizar.setForeground(java.awt.Color.black);
        add(jTFNitEmpresaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 340, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Telefono");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Nombre Vendedor");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Telefono Vendedor");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        jTFTelefonoEmpresaActualizar.setBackground(java.awt.Color.white);
        jTFTelefonoEmpresaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoEmpresaActualizar.setForeground(java.awt.Color.black);
        add(jTFTelefonoEmpresaActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 350, -1));

        jTFVendedorActualizar.setBackground(java.awt.Color.white);
        jTFVendedorActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFVendedorActualizar.setForeground(java.awt.Color.black);
        add(jTFVendedorActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 350, -1));

        jTFTelefonoVendedorActualizar.setBackground(java.awt.Color.white);
        jTFTelefonoVendedorActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoVendedorActualizar.setForeground(java.awt.Color.black);
        add(jTFTelefonoVendedorActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 350, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Descripcion");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, -1, -1));

        jTADescripcionEmpresaActualizar.setBackground(java.awt.Color.white);
        jTADescripcionEmpresaActualizar.setColumns(20);
        jTADescripcionEmpresaActualizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTADescripcionEmpresaActualizar.setForeground(java.awt.Color.black);
        jTADescripcionEmpresaActualizar.setRows(5);
        jScrollPane1.setViewportView(jTADescripcionEmpresaActualizar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 360, 100));

        jBCancelarActualizar.setBackground(java.awt.Color.red);
        jBCancelarActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarActualizar.setForeground(java.awt.Color.black);
        jBCancelarActualizar.setText("Cancelar");
        jBCancelarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActualizarActionPerformed(evt);
            }
        });
        add(jBCancelarActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 270, -1, -1));

        jBAceptarActualizar.setBackground(java.awt.Color.green);
        jBAceptarActualizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarActualizar.setForeground(java.awt.Color.black);
        jBAceptarActualizar.setText("Aceptar");
        jBAceptarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActualizarActionPerformed(evt);
            }
        });
        add(jBAceptarActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1158, 360, 110, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, -20, -1, -1));

        jTProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTProveedores);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 750, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void jTProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProveedoresMouseClicked
        // TODO add your handling code here:
        
        int seleccionar = jTProveedores.rowAtPoint(evt.getPoint());
        
        this.idProveedor=(int) jTProveedores.getValueAt(seleccionar, 0);
        
        String nombreEmpresa = (String) jTProveedores.getValueAt(seleccionar,1);
        jTFNombreEmpresaActualizar.setText(nombreEmpresa);
        String direccion = (String) jTProveedores.getValueAt(seleccionar,2);
        jTFDIreccionEmpresaActualizar.setText(direccion);
        String nitEmpresa = (String) jTProveedores.getValueAt(seleccionar, 3);
        jTFNitEmpresaActualizar.setText(nitEmpresa);
        String telefono = (String) jTProveedores.getValueAt(seleccionar, 4);
        jTFTelefonoEmpresaActualizar.setText(telefono);
        String descripcion = (String) jTProveedores.getValueAt(seleccionar, 5);
        jTADescripcionEmpresaActualizar.setText(descripcion);
        String vendedor = (String) jTProveedores.getValueAt(seleccionar,6);
        jTFVendedorActualizar.setText(vendedor);
        String telefonoVendedor = (String) jTProveedores.getValueAt(seleccionar,7);
        jTFTelefonoVendedorActualizar.setText(telefonoVendedor);
        
        
        
        
        
    }//GEN-LAST:event_jTProveedoresMouseClicked

    private void jBAceptarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActualizarActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        
        String nombreEmpresa= jTFNombreEmpresaActualizar.getText();
        String direccion = jTFDIreccionEmpresaActualizar.getText();
        String nitempresa = jTFNitEmpresaActualizar.getText();
        String telefonoEmpresa = jTFTelefonoEmpresaActualizar.getText();
        String nombreVendedor = jTFVendedorActualizar.getText();
        String telefonoVendedor = jTFTelefonoVendedorActualizar.getText();
        String descripcion = jTADescripcionEmpresaActualizar.getText();
        
        try {
            
            String queryactualizar ="UPDATE proveedor SET nombreempresa = '"+nombreEmpresa+"',direccion='"+direccion+"',nit='"+nitempresa+"',telefono='"+telefonoEmpresa+"',descripcion='"+descripcion+"',vendedor='"+nombreVendedor+"',telefonovendedor='"+telefonoVendedor+"' WHERE idproveedor = '"+idProveedor+"'";
            
            st = conexion.getConection().prepareStatement(queryactualizar);
            st.executeUpdate();
            jTFNombreEmpresaActualizar.setText("");
            jTFDIreccionEmpresaActualizar.setText("");
            jTFNitEmpresaActualizar.setText("");
            jTFTelefonoEmpresaActualizar.setText("");
            jTFVendedorActualizar.setText("");
            jTFTelefonoVendedorActualizar.setText("");
            jTADescripcionEmpresaActualizar.setText("");
            try {
            String query = "SELECT * FROM proveedor";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTProveedores.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE EMRPRESA","DIRECCION", "NIT", "TELEFONO","DESCRIPCION","VENDEDOR","TELEFONO VENDEDOR"});

            while (rs.next()){
             
                dfmproducto.addRow(new Object[] {rs.getInt("idproveedor"),rs.getString("nombreempresa"),rs.getString("direccion"),rs.getString("nit"),rs.getString("telefono"),rs.getString("descripcion"),rs.getString("vendedor"),rs.getString("telefonovendedor")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
        }
            
            
            
        }catch(SQLException ex){
            System.out.println(ex.toString());
        }
        
        
        
    }//GEN-LAST:event_jBAceptarActualizarActionPerformed

    private void jBCancelarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActualizarActionPerformed
        // TODO add your handling code here:
        
            jTFNombreEmpresaActualizar.setText("");
            jTFDIreccionEmpresaActualizar.setText("");
            jTFNitEmpresaActualizar.setText("");
            jTFTelefonoEmpresaActualizar.setText("");
            jTFVendedorActualizar.setText("");
            jTFTelefonoVendedorActualizar.setText("");
            jTADescripcionEmpresaActualizar.setText("");
    }//GEN-LAST:event_jBCancelarActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarActualizar;
    private javax.swing.JButton jBCancelarActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescripcionEmpresaActualizar;
    private javax.swing.JTextField jTFDIreccionEmpresaActualizar;
    private javax.swing.JTextField jTFNitEmpresaActualizar;
    private javax.swing.JTextField jTFNombreEmpresaActualizar;
    private javax.swing.JTextField jTFTelefonoEmpresaActualizar;
    private javax.swing.JTextField jTFTelefonoVendedorActualizar;
    private javax.swing.JTextField jTFVendedorActualizar;
    private javax.swing.JTable jTProveedores;
    // End of variables declaration//GEN-END:variables
}
