/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPProveedorBorrar extends javax.swing.JPanel {

    /**
     * Creates new form JPProveedorBorrar
     */
    
    PreparedStatement st;
    ResultSet rs;
    int idProveedor;
    
    
    public JPProveedorBorrar() {
        initComponents();
        
        //MOSTRAR TABLA CON LOS PROVEEDORES
          try {
            String query = "SELECT * FROM proveedor";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTProveedores.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE EMRPRESA","DIRECCION", "NIT", "TELEFONO","DESCRIPCION","VENDEDOR","TELEFONO VENDEDOR"});

            while (rs.next()){
             
                dfmproducto.addRow(new Object[] {rs.getInt("idproveedor"),rs.getString("nombreempresa"),rs.getString("direccion"),rs.getString("nit"),rs.getString("telefono"),rs.getString("descripcion"),rs.getString("vendedor"),rs.getString("telefonovendedor")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
     
        }

//***************************************************   

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombreEmpresaBorrar = new javax.swing.JTextField();
        jTFDIreccionEmpresaBorrar = new javax.swing.JTextField();
        jTFNitEmpresaBorrar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFTelefonoEmpresaBorrar = new javax.swing.JTextField();
        jTFVendedorBorrar = new javax.swing.JTextField();
        jTFTelefonoVendedorBorrar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionEmpresaBorrar = new javax.swing.JTextArea();
        jBCancelarBorrar = new javax.swing.JButton();
        jBAceptarBorrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProveedores = new javax.swing.JTable();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Borrar Proveedor");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre Empresa");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Direccion");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("NIT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        jTFNombreEmpresaBorrar.setBackground(java.awt.Color.white);
        jTFNombreEmpresaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreEmpresaBorrar.setForeground(java.awt.Color.black);
        add(jTFNombreEmpresaBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 330, -1));

        jTFDIreccionEmpresaBorrar.setBackground(java.awt.Color.white);
        jTFDIreccionEmpresaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFDIreccionEmpresaBorrar.setForeground(java.awt.Color.black);
        add(jTFDIreccionEmpresaBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 330, -1));

        jTFNitEmpresaBorrar.setBackground(java.awt.Color.white);
        jTFNitEmpresaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNitEmpresaBorrar.setForeground(java.awt.Color.black);
        add(jTFNitEmpresaBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 330, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Telefono");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Nombre Vendedor");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Telefono Vendedor");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, -1, -1));

        jTFTelefonoEmpresaBorrar.setBackground(java.awt.Color.white);
        jTFTelefonoEmpresaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoEmpresaBorrar.setForeground(java.awt.Color.black);
        add(jTFTelefonoEmpresaBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 300, 340, -1));

        jTFVendedorBorrar.setBackground(java.awt.Color.white);
        jTFVendedorBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFVendedorBorrar.setForeground(java.awt.Color.black);
        add(jTFVendedorBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 340, -1));

        jTFTelefonoVendedorBorrar.setBackground(java.awt.Color.white);
        jTFTelefonoVendedorBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFTelefonoVendedorBorrar.setForeground(java.awt.Color.black);
        add(jTFTelefonoVendedorBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 340, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Descripcion");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, -1));

        jTADescripcionEmpresaBorrar.setBackground(java.awt.Color.white);
        jTADescripcionEmpresaBorrar.setColumns(20);
        jTADescripcionEmpresaBorrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTADescripcionEmpresaBorrar.setForeground(java.awt.Color.black);
        jTADescripcionEmpresaBorrar.setRows(5);
        jScrollPane1.setViewportView(jTADescripcionEmpresaBorrar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 350, 100));

        jBCancelarBorrar.setBackground(java.awt.Color.red);
        jBCancelarBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarBorrar.setForeground(java.awt.Color.black);
        jBCancelarBorrar.setText("Cancelar");
        jBCancelarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarBorrarActionPerformed(evt);
            }
        });
        add(jBCancelarBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 620, -1, -1));

        jBAceptarBorrar.setBackground(java.awt.Color.green);
        jBAceptarBorrar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarBorrar.setForeground(java.awt.Color.black);
        jBAceptarBorrar.setText("Aceptar");
        jBAceptarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarBorrarActionPerformed(evt);
            }
        });
        add(jBAceptarBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, -20, -1, -1));

        jTProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTProveedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTProveedores);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 750, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void jTProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTProveedoresMouseClicked
        // TODO add your handling code here:

        int seleccionar = jTProveedores.rowAtPoint(evt.getPoint());

        this.idProveedor=(int) jTProveedores.getValueAt(seleccionar, 0);

        String nombreEmpresa = (String) jTProveedores.getValueAt(seleccionar,1);
        jTFNombreEmpresaBorrar.setText(nombreEmpresa);
        String direccion = (String) jTProveedores.getValueAt(seleccionar,2);
        jTFDIreccionEmpresaBorrar.setText(direccion);
        String nitEmpresa = (String) jTProveedores.getValueAt(seleccionar, 3);
        jTFNitEmpresaBorrar.setText(nitEmpresa);
        String telefono = (String) jTProveedores.getValueAt(seleccionar, 4);
        jTFTelefonoEmpresaBorrar.setText(telefono);
        String descripcion = (String) jTProveedores.getValueAt(seleccionar, 5);
        jTADescripcionEmpresaBorrar.setText(descripcion);
        String vendedor = (String) jTProveedores.getValueAt(seleccionar,6);
        jTFVendedorBorrar.setText(vendedor);
        String telefonoVendedor = (String) jTProveedores.getValueAt(seleccionar,7);
        jTFTelefonoVendedorBorrar.setText(telefonoVendedor);

    }//GEN-LAST:event_jTProveedoresMouseClicked

    private void jBAceptarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarBorrarActionPerformed
        // TODO add your handling code here:
        try {
            String queryBorrar = "DELETE FROM proveedor WHERE idproveedor='"+idProveedor+"'";
            
            st=conexion.getConection().prepareStatement(queryBorrar);
            st.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"El proveedor fue borrado con exito", "!Aviso!",2);
            //MOSTRAR TABLA CON LOS PROVEEDORES
          try {
            String query = "SELECT * FROM proveedor";
            st= conexion.getConection().prepareStatement(query);
            rs = st.executeQuery();
            
            DefaultTableModel dfmproducto = new DefaultTableModel();
            
            jTProveedores.setModel(dfmproducto);
            dfmproducto.setColumnIdentifiers(new Object[] {"ID","NOMBRE EMRPRESA","DIRECCION", "NIT", "TELEFONO","DESCRIPCION","VENDEDOR","TELEFONO VENDEDOR"});

            while (rs.next()){
             
                dfmproducto.addRow(new Object[] {rs.getInt("idproveedor"),rs.getString("nombreempresa"),rs.getString("direccion"),rs.getString("nit"),rs.getString("telefono"),rs.getString("descripcion"),rs.getString("vendedor"),rs.getString("telefonovendedor")});
                
            }
            
            
        } catch(SQLException ex){
            
            System.out.println(ex.toString());
            
     
        }

          
          
//**************************************************   
          jTFNombreEmpresaBorrar.setText("");
          jTFDIreccionEmpresaBorrar.setText("");
          jTFNitEmpresaBorrar.setText("");
          jTFTelefonoEmpresaBorrar.setText("");
          jTFVendedorBorrar.setText("");
          jTFTelefonoVendedorBorrar.setText("");
          jTADescripcionEmpresaBorrar.setText("");
          
            
        }catch(SQLException ex){
            
            System.out.println(ex.toString());
        }
        
        
        
    }//GEN-LAST:event_jBAceptarBorrarActionPerformed

    private void jBCancelarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarBorrarActionPerformed
        // TODO add your handling code here:
          jTFNombreEmpresaBorrar.setText("");
          jTFDIreccionEmpresaBorrar.setText("");
          jTFNitEmpresaBorrar.setText("");
          jTFTelefonoEmpresaBorrar.setText("");
          jTFVendedorBorrar.setText("");
          jTFTelefonoVendedorBorrar.setText("");
          jTADescripcionEmpresaBorrar.setText("");
        
    }//GEN-LAST:event_jBCancelarBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarBorrar;
    private javax.swing.JButton jBCancelarBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescripcionEmpresaBorrar;
    private javax.swing.JTextField jTFDIreccionEmpresaBorrar;
    private javax.swing.JTextField jTFNitEmpresaBorrar;
    private javax.swing.JTextField jTFNombreEmpresaBorrar;
    private javax.swing.JTextField jTFTelefonoEmpresaBorrar;
    private javax.swing.JTextField jTFTelefonoVendedorBorrar;
    private javax.swing.JTextField jTFVendedorBorrar;
    private javax.swing.JTable jTProveedores;
    // End of variables declaration//GEN-END:variables
}
