/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopuntodeventa;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import packageconexion.conexion;

/**
 *
 * @author Administrator
 */
public class JPRoles extends javax.swing.JPanel {

    /**
     * Creates new form JPRoles
     */
    public JPRoles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFNombreRol = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcionRol = new javax.swing.JTextArea();
        jBCancelarRol = new javax.swing.JButton();
        jBAceptarRol = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopuntodeventa/logo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Registro de roles");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Nombre");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Descripcion");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        jTFNombreRol.setBackground(java.awt.Color.white);
        jTFNombreRol.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTFNombreRol.setForeground(java.awt.Color.black);
        add(jTFNombreRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 310, 30));

        jTADescripcionRol.setBackground(java.awt.Color.white);
        jTADescripcionRol.setColumns(20);
        jTADescripcionRol.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTADescripcionRol.setRows(5);
        jScrollPane1.setViewportView(jTADescripcionRol);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 310, 110));

        jBCancelarRol.setBackground(java.awt.Color.red);
        jBCancelarRol.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelarRol.setForeground(java.awt.Color.black);
        jBCancelarRol.setText("Cancelar");
        jBCancelarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarRolActionPerformed(evt);
            }
        });
        add(jBCancelarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 402, 120, 50));

        jBAceptarRol.setBackground(java.awt.Color.green);
        jBAceptarRol.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBAceptarRol.setForeground(java.awt.Color.black);
        jBAceptarRol.setText("Aceptar");
        jBAceptarRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarRolActionPerformed(evt);
            }
        });
        add(jBAceptarRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 402, 120, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jBAceptarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarRolActionPerformed
        // TODO add your handling code here:
        PreparedStatement consulta;
        ResultSet resultado;
        
         String nombre = jTFNombreRol.getText();
        String descripcion = jTADescripcionRol.getText();
       //********************************************************
       //VALIDACION
        if (nombre.trim().equals("")){
            
            JOptionPane.showMessageDialog(null, "Debe ingresar el nombre del rol","ERROR",2);
            
            
        }else if (descripcion.trim().equals("")){
            JOptionPane.showMessageDialog(null, "Debe ingresar la descripcion del rol","ERROR",2);
            
            
        }
        //****************************************************************************************
        else {
            
             try {
            String query = "INSERT INTO rol(nombre,descripcion) VALUES ('"+nombre+"','"+descripcion+"')";
            
            consulta = conexion.getConection().prepareStatement(query);
            consulta.executeUpdate();
            jTFNombreRol.setText("");
            jTADescripcionRol.setText("");
            
            
            
            }catch(SQLException excepcion){

                System.out.println(excepcion.toString());
            }
        }

        
        
    }//GEN-LAST:event_jBAceptarRolActionPerformed

    private void jBCancelarRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarRolActionPerformed
        // TODO add your handling code here:
        
        jTFNombreRol.setText("");
        jTADescripcionRol.setText("");
    }//GEN-LAST:event_jBCancelarRolActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptarRol;
    private javax.swing.JButton jBCancelarRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcionRol;
    private javax.swing.JTextField jTFNombreRol;
    // End of variables declaration//GEN-END:variables
}
